import { useState, useEffect } from 'react';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Button } from '@/components/ui/button';
import { Switch } from '@/components/ui/switch';
import { Info, Quote, Image, Phone, Video } from 'lucide-react';
import { cn } from '@/lib/utils';
import { getMindProfile, updateMindProfile } from '@/db/api';
import { useToast } from '@/hooks/use-toast';
import { MindProfile } from '@/types/types';

interface ExperienceSettingsViewProps {
    profileId: string;
    initialData?: MindProfile;
}

const ExperienceSettingsView = ({ profileId, initialData }: ExperienceSettingsViewProps) => {
    const { toast } = useToast();
    const settings = initialData?.experience_settings || initialData?.response_settings || {};
    const [initialMessage, setInitialMessage] = useState(settings.initialMessage || "Hey Platinum Magician, this is Mitesh AI, how can i help you?");
    const [noAnswerMessage, setNoAnswerMessage] = useState(settings.noAnswerMessage || "I'm sorry, I don't have the answer to that right now. In the meantime, feel free to explore our website at https://www.miteshkhatri.com or let me know if there's anything else I can assist with!");

    // Experience State
    const [showCitations, setShowCitations] = useState(settings.showCitations ?? true);
    const [enableFileSending, setEnableFileSending] = useState(settings.enableFileSending ?? true);
    const [enableVoiceCalling, setEnableVoiceCalling] = useState(settings.enableVoiceCalling ?? true);
    const [enableVideoCalling, setEnableVideoCalling] = useState(settings.enableVideoCalling ?? false);

    // Advanced Settings State
    const [showDisclaimer, setShowDisclaimer] = useState(settings.showDisclaimer ?? true);
    const [disclaimerText, setDisclaimerText] = useState(settings.disclaimerText || "This is an AI assistant based on Mitesh's teachings and content. Responses are generated by AI and do not replace personalized coaching or professional advice.");
    const [isLoading, setIsLoading] = useState(false);

    useEffect(() => {
        loadProfile();
    }, [profileId]);

    const loadProfile = async () => {
        try {
            const profile = await getMindProfile(profileId);
            const settings = profile?.experience_settings || profile?.response_settings || {};

            setInitialMessage(settings.initialMessage || "Hey Platinum Magician, this is Mitesh AI, how can i help you?");
            setNoAnswerMessage(settings.noAnswerMessage || "I'm sorry, I don't have the answer to that right now. In the meantime, feel free to explore our website at https://www.miteshkhatri.com or let me know if there's anything else I can assist with!");
            setShowCitations(settings.showCitations ?? true);
            setEnableFileSending(settings.enableFileSending ?? true);
            setEnableVoiceCalling(settings.enableVoiceCalling ?? true);
            setEnableVideoCalling(settings.enableVideoCalling ?? false);
            setShowDisclaimer(settings.showDisclaimer ?? true);
            setDisclaimerText(settings.disclaimerText || "This is an AI assistant based on Mitesh's teachings and content. Responses are generated by AI and do not replace personalized coaching or professional advice.");
        } catch (error) {
            console.error('Error loading profile:', error);
        }
    };

    const handleSave = async () => {
        setIsLoading(true);
        try {
            await updateMindProfile({
                experience_settings: {
                    initialMessage,
                    noAnswerMessage,
                    showCitations,
                    enableFileSending,
                    enableVoiceCalling,
                    enableVideoCalling,
                    showDisclaimer,
                    disclaimerText
                }
            }, profileId);
            toast({
                title: "Saved",
                description: "Experience settings updated successfully.",
            });
        } catch (error) {
            console.error('Error saving profile:', error);
            toast({
                title: "Error",
                description: "Failed to save changes.",
                variant: "destructive",
            });
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="max-w-4xl mx-auto p-8 space-y-8">
            <div className="flex items-center justify-between">
                <div className="space-y-1">
                    <h2 className="text-2xl font-semibold">Experience Settings</h2>
                    <p className="text-muted-foreground">Configure how your Clone interacts with users.</p>
                </div>
                <Button onClick={handleSave} disabled={isLoading} className="rounded-full px-8">
                    {isLoading ? "Saving..." : "Save Changes"}
                </Button>
            </div>

            <div className="space-y-6">
                <div className="flex items-center gap-2">
                    <h3 className="text-lg font-medium">Message Settings</h3>
                    <Info className="w-4 h-4 text-muted-foreground" />
                </div>

                <div className="space-y-6">
                    <div className="space-y-2">
                        <div className="flex items-center gap-2">
                            <Quote className="w-4 h-4 text-orange-500" />
                            <Label>Initial Message</Label>
                        </div>
                        <Textarea
                            value={initialMessage}
                            onChange={(e) => setInitialMessage(e.target.value)}
                            className="min-h-[80px] resize-none"
                            placeholder="The first message users see when they start a conversation..."
                        />
                        <p className="text-xs text-muted-foreground">This is the first message users will see when they open the chat.</p>
                    </div>

                    <div className="space-y-2">
                        <div className="flex items-center gap-2">
                            <Quote className="w-4 h-4 text-orange-500" />
                            <Label>No Answer Message</Label>
                        </div>
                        <Textarea
                            value={noAnswerMessage}
                            onChange={(e) => setNoAnswerMessage(e.target.value)}
                            className="min-h-[100px] resize-none"
                            placeholder="The message shown when your clone doesn't have an answer..."
                        />
                        <p className="text-xs text-muted-foreground">Displayed when your clone can't find a relevant answer in the knowledge base.</p>
                    </div>
                </div>
            </div>

            <div className="space-y-6">
                <div className="flex items-center gap-2">
                    <h3 className="text-lg font-medium">User Experience</h3>
                    <Info className="w-4 h-4 text-muted-foreground" />
                </div>

                <div className="space-y-4">
                    <div className="flex items-center justify-between p-4 border rounded-lg">
                        <div className="space-y-0.5">
                            <Label className="text-base">Show Citations</Label>
                            <p className="text-sm text-muted-foreground">Display source references in responses</p>
                        </div>
                        <Switch checked={showCitations} onCheckedChange={setShowCitations} className="data-[state=checked]:bg-orange-500" />
                    </div>

                    <div className="flex items-center justify-between p-4 border rounded-lg">
                        <div className="flex items-center gap-2">
                            <Image className="w-5 h-5 text-orange-500" />
                            <div className="space-y-0.5">
                                <Label className="text-base">Enable File Sending</Label>
                                <p className="text-sm text-muted-foreground">Allow users to upload files and images</p>
                            </div>
                        </div>
                        <Switch checked={enableFileSending} onCheckedChange={setEnableFileSending} className="data-[state=checked]:bg-orange-500" />
                    </div>

                    <div className="flex items-center justify-between p-4 border rounded-lg">
                        <div className="flex items-center gap-2">
                            <Phone className="w-5 h-5 text-orange-500" />
                            <div className="space-y-0.5">
                                <Label className="text-base">Enable Voice Calling</Label>
                                <p className="text-sm text-muted-foreground">Allow users to voice call your clone</p>
                            </div>
                        </div>
                        <Switch checked={enableVoiceCalling} onCheckedChange={setEnableVoiceCalling} className="data-[state=checked]:bg-orange-500" />
                    </div>

                    <div className="flex items-center justify-between p-4 border rounded-lg">
                        <div className="flex items-center gap-2">
                            <Video className="w-5 h-5 text-orange-500" />
                            <div className="space-y-0.5">
                                <Label className="text-base">Enable Video Calling</Label>
                                <p className="text-sm text-muted-foreground">Allows users to video call your clone. A video avatar must be setup.</p>
                            </div>
                        </div>
                        <Switch checked={enableVideoCalling} onCheckedChange={setEnableVideoCalling} className="data-[state=checked]:bg-orange-500" />
                    </div>
                </div>
            </div>

            <div className="space-y-6">
                <div className="flex items-center gap-2">
                    <h3 className="text-lg font-medium">Advanced Settings</h3>
                    <Info className="w-4 h-4 text-muted-foreground" />
                </div>

                <div className="space-y-6">
                    <div className="space-y-4">
                        <div className="flex items-center justify-between">
                            <div className="flex items-center gap-2">
                                <Label className="text-base">Disclaimer</Label>
                                <span className="px-2 py-0.5 text-xs bg-muted text-muted-foreground rounded-full">Optional</span>
                            </div>
                            <Switch checked={showDisclaimer} onCheckedChange={setShowDisclaimer} className="data-[state=checked]:bg-orange-500" />
                        </div>
                        <p className="text-sm text-muted-foreground">
                            This banner appears at the top of the chat interface if specified.
                        </p>
                        {showDisclaimer && (
                            <div className="relative">
                                <Textarea
                                    value={disclaimerText}
                                    onChange={(e) => setDisclaimerText(e.target.value)}
                                    className="min-h-[100px] resize-none"
                                    maxLength={400}
                                />
                                <span className={cn("absolute bottom-2 right-2 text-xs", disclaimerText.length > 400 ? "text-red-500" : "text-muted-foreground")}>
                                    {disclaimerText.length}/400
                                </span>
                            </div>
                        )}
                    </div>

                    <div className="space-y-4 pt-4 border-t">
                        <div className="flex items-center gap-2">
                            <Label className="text-base">Disable your Talk Page</Label>
                            <span className="px-2 py-0.5 text-xs bg-red-100 text-red-600 rounded-full">Danger Zone</span>
                        </div>
                        <p className="text-sm text-muted-foreground">
                            Disabling your Talk Page will prevent all users from interacting with your clone. This action affects both new and existing users.
                        </p>
                        <Button variant="destructive" className="bg-red-100 text-red-600 hover:bg-red-200 border-none">
                            Disable Talk Page
                        </Button>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default ExperienceSettingsView;
